### PR TITLE
Added file sharing support to EMUBrowser.

### PR DESCRIPTION
**Pull request by MrStargazer**
Hi,

i have added file sharing support to the EMUBrowser file list, so you can easily share your files with airdrop on different devices or you can even send your pearls via iMessage or Email. Just swipe left on each entry and click the "share"-Button.

### CODE REVIEW

**Comment by emufreak** [comment]
First. Welcome to the project :-) I'll test this as soon as I have a moment and then merge this.

**Comment by MrStargazer** [comment]
Thank you.  :-)

Since I have so much fun with this emulator in the last few weeks, i'm glad to return something. 

This is more than just software :-)

**Comment by simontoens** [comment]
"This is more than just software", well said @MrStargazer!

**Comment by mithrendal** [comment]
For me it is profound cultural joy in its purest thoroughly form. Isn't it? ;-)

**Comment by emufreak** [comment]
Thanks for this. I'll commit now to be able to rename the branch.

**Comment by simontoens** [comment]
I can't figure out how I can @mention all 3 of you in GitHub, except on a pull request (if you know of a way please let me know), so I am going to hijack this pull request for this message, I hope that is ok :)

@emufreak @mithrendal @MrStargazer 

I have spent a fair amount of time on trying to get hd support to work and I would appreciate another (or two other ideally) pair of eyes to have a look what I have so far.  I am running into core emulator problems that I just don't know enough about.  I am hoping one of you understands the core emulator code a bit better (or perhaps you know somebody who does) and hopefully you have a little time to have a look.

Let me try to summarize where I am at:
- All the work I did is in this branch: https://github.com/simontoens/iAmiga/tree/1.1.0b1_hd
- This branch includes an empty hard file, empty.hdf for testing.
- I am basing the work on uae4all2 that emufreak has here: https://github.com/emufreak/uae4all2

What I did:
- I made sure that the uae4all2 hd support actually works by building it and running it on an android emulator (had to install a bunch of stuff, google a lot etc).  Finally I was able to confirm that, when using a hardfile, hd support works with kick1.3, i.e. on the android emulator I was able to boot workbench and see a hard drive icon on the desktop.  I was not able to get uae4all2's directory hd support to work but that doesn't really matter I think - a hardfile is fine (btw I created the hardfile using what's described here: http://lallafa.de/blog/2012/01/mastering-adfhdf-images-with-xdftool/)
- I copied the h/cpp files that seem relevant from uae4all to iAmiga and tweaked things so they compile.
- After debugging a lot and compare method executions between uae4all on android and iAmiga I narrowed the problem down: functions like filesys_dev_bootfilesys and filesys_diagentry (both in filesys.cpp) are not being called in the iAmiga version.
- The complicated part is that these functions are "registered" and are then expected to be called back from the emulated AmigaOS (at least that is my understanding).  
- The registration uses code like this:     calltrap (deftrap2 (filesys_diagentry, 0, "filesys_diagentry")); and also:     do_put_mem_long ((uae_u32 *)(expamem + 0x1102), (ROM_filesys_diagentry));
- The code in my branch is in a state where these functions should get called regardless of whether a hard drive has been configured (again, I have verified this on android).  So I can confirm that the hd setup code is not the real problem here (at least not right now).
- I don't even know about how I should go about debugging this (but I would be very happy to learn)

If any of you has some time and some energy to have a look, that would be really great.  I'd be happy to provide more detailed information about everything I have tried to far.  If you want I can also tell you what I had to do to get uae4all2 to run on my mac.  I just really want to see the hd support working on iOS...

**Comment by mithrendal** [comment]
@simontoens Hi simon, I do recapitulate. You did take the hd related classes from uae4all2 and added these into the iAmiga uae emu classes. I think that this approach is perfectly none time consuming when transfering features isolated in a couple of lines or one or three classes. But I feel that if you have got a lot of classes maybe from 5 to 10 and the feature is spreaded over loads of codelines, then it might be more time consuming to integrated these into the iAmiga than to replace the iAmiga uae classes with the complete uae4all2 emu classes. 

What do you think ?

**Comment by MrStargazer** [comment]
@simontoens  Sry simon, i would like to help you with your problem, but i've definitely no knowledge  in implementing emulator code. But i think that mithrendals proposal could be good approach to solve the problem. Beside this we would get AGA-support with the complete usage of uae4all2.

**Comment by simontoens** [comment]
Thanks @mithrendal and @MrStargazer - yes taking all the code from uae4all2 instead of only the hd related files is probably the best way to go at this point.  I tried to avoid that because I know that it won't just work and compile and run...and it would potentially break things we already got working.  But I can't think of anything else.  @emufreak has done something similar before to get iUAE started... @emufreak what do you think?

I will probably work on a smaller feature first and then have another look at this problem.  Unless somebody else wants to try?  I would like to create an issue listing everything I have done so far for hd support...once @emufreak enables issues ... :)

**Comment by emufreak** [comment]
Hi @simontoens @MrStargazer @mithrendal 

I have some time today and I'd like to give it a go. I have some Ideas. I think with a bit of luck it might be easy to fix. I'll let you know if it worked.

**Comment by emufreak** [comment]
Hi @simontoens @mithrendal @MrStargazer 

I think I fixed. I ported memory.cpp from uae4all2. Now it shows the Harddisk. Simon I sent you the cpp-file.

**Comment by mithrendal** [comment]
Great stuff @emufreak . I bet you made simon very happy 👍.

**Comment by simontoens** [comment]
It works!!!! This is so great, yes I am very happy!!!  Thanks so much @emufreak for the fix.

I will clean up what I have a bit, add some UI and then send a pull request.  Oh I also need to test this of course, I think Monkey Island 2 is a good way to test hd support :).  Speaking of MI2, have you all seen Ron Gilbert's new game? https://blog.thimbleweedpark.com

**Comment by MrStargazer** [comment]
A small step for you but a huge step for mankind and especially for all retro fans out there. Good job @emufreak.

**Comment by emufreak** [comment]
@simontoens I'm very happy too. Thanks for all the Work you put into this. Have fun playing Monkey Island 2. It's a great game. 

No I had no Idea about Timbleweedpark. Great that Ron Gilbert still makes Classic Adventure Games! Maybe someone writes an Amiga Port so we can play it in iUAE :-)

**Pull request merged**
