### PR TITLE
Issue #29: limited hard drive support

### PR DESCRIPTION
**Pull request by simontoens**
Only a single .hdf file can be mounted.  Ported from uae4all2.
Special thanks to @emufreak for debugging help.

### CODE REVIEW

**Comment by emufreak** [comment]
Hi @simontoens Many thanks. I was looking forward to this for quite a while.

**Comment by emufreak** [comment]
By the way thit Monkey Island 2 work?

**Comment by simontoens** [comment]
@emufreak I couldn't get the install program of MI2 to work for some reason.  When it asks where to install, it does not understand when I enter "dh0:".  Workbench/CLI and MI1 are fine with "dh0:" so I am not sure what is going on - it may be my version of MI2.  I am planning to look at it some more.

**Comment by simontoens** [comment]
@emufreak I got MI2 to run fine from HD by manually copying all the disks and then running 11 "assign" statements.

**Pull request merged**
