### PR TITLE
1.1.0b1 joy

### PR DESCRIPTION
**Pull request by simontoens**
Hi @emufreak - this is a fairly large pull request...

The important changes are:
- Fix emulator crash that happened with iOS 9.
- Handle restoring a state file that has a stale path to an adf file; if the adf file exists on the iDevice, the path is updated to the new adf location.
- Also look for kick rom file in the user documents directory; this allows copying the rom using iTunes.
- Add a new view for configuring the on-screen joypad:
  - Optionally show the location of the joypad area and the location of the fire button on screen.
  - Add autofire option.
  - Add a way to configure buttons (on screen areas) that trigger a key to be pressed.

### CODE REVIEW

**Comment by emufreak** [comment]
Hi @simontoens I'm also working on a pull request (That's almos complete in fact). I did very similiar changes on the onscreeen joypad. (Show Joypad areas onscreen, if it gets activated. Visualize Button touch. Programmable buttons.) I think it won't be possible to simply merge those 

This is myy Suggestion:

I will upload my changes as soon as I can and have a look at your version of the app. Then we can discuss how to proceed for example on skype chat.

**Comment by simontoens** [comment]
Ah...maybe "great minds think alike"? :)

Ok have a look at my 1.1.0b1_joy branch and we'll figure it out...

**Comment by emufreak** [comment]
Hi @simontoens 

I  uploaded my commits on Monday. It works fairly well there is still a lot of bug fixing to do however. This should give you a change to look at it.

**Comment by simontoens** [comment]
Thanks @emufreak, I had a look.  As far as I can tell my change is further along because it lets you map any key and it lets you configure where on the screen the key "button" appears.  Did you have a chance to look at my 1.1.0b1_joy branch?  
This pull request also has some other unrelated things, so I think I will start by creating individual pull requests for those.

**Comment by emufreak** [comment]
Hi @simontoens 

I just had a look at your pull request. I do see advantages in both solutions actually. I think it it is a question of taste and the kind of games you play in the end (The same applies to physical Joypads actually). 

So I’d say let the users decide and implement both options. This will require some changes in the Settings GUI but I think this should be doable.

**Comment by emufreak** [comment]
I just had an Idea. I think your onscreen buttons might be very useful for some mousecontrolled games too. For example Lemmings is almost unplayable because you are always to slow choosing the appropriate action using the onscreen trackpad. Or for an Adventuregame like Monkey Island it could be used to put the most often used commands on screen (Use, Give To etc). 

We could add it as an exra layer onscreen that doesnt interfere with mouse or joypad. Then we could use it for both. 

I think this would add a lot of extra value to this.

**Comment by simontoens** [comment]
That makes sense, I can refactor it that way.  You are right, the ability to add onscreen buttons should not be tied to the joypad settings.

**Comment by simontoens** [comment]
...therefore I will close this pull request.

**Pull request closed without merging**
