### PR TITLE
added vertical stretching for use of unused space at the bottom of the screen

### PR DESCRIPTION
**Pull request by mithrendal**
Uhh, now I got it. I had also to delete my wrong commits via git rebase -i HEAD~2 

Now everything looks fine :-)   I would say. Only the 5 relevant files are in the pull request. Learned a lot about git. Thank you simon for your assistance ;-)

### CODE REVIEW

**Comment by simontoens** [comment]
Looks way better!  git is not the most usable thing but once you get used to it, it is great.

One comment: most (all?) settings are persisted in Setting.mm, so that when you kill and restart the app, everything more or less looks they way you configured it previously.  Might be good to hook up your new vertical space setting also so that it is persisted.  Should be pretty obvious if you look at Settings.mm.

**Comment by simontoens** [comment]
@mithrendal @emufreak on a totally unrelated note, but I don't know how else I can @mention both of you: I think it would be helpful to enable GitHub "issues" for this repository so we can file bugs and todo items.  It would also allow us to more easily see who is working on what.  I think enabling issues is a repository setting... (?).  I have it enabled for my own repositories but it doesn't seem to be on here.  @emufreak could you check and see if you can enable issues?  Thanks!

**Comment by mithrendal** [comment]
Vertical Stretch Setting persisted 😊

**Comment by simontoens** [comment]
Looks good!

**Comment by emufreak** [comment]
@mithrendal @simontoens Thanks for the commit and cleaning it up. I will merge it now.

**Pull request merged**
