### PR TITLE
added the ability to add an extra vertical stretch by n pixel

### PR DESCRIPTION
**Pull request by mithrendal**
to get use of unused space in a lot of games at bottom of the screen.

But you can ignore the file iUAE.xcodeproj/project.pbxproj. I don't know how to exclude it from the pull request. Xcode asked me to commit everything before I had been able to pull your changes (or the ones of simon). How can I do this better next time ?

### CODE REVIEW

**Comment by simontoens** [comment]
Hi @mithrendal, there is actually no way to ignore something in a pull request, it is all or nothing.  So the best approach would be that you re-create a pull request with only the changes you want to commit.

I use git from the command line, I do not use the Xcode integration.  Git from the command like works very well.  You can probably do something like this to proceed:

In the branch where you made your commit:
git reset --soft HEAD~ (this will undo your last commit and move the files back to the staging area)
git status (to see all the files that are staged to be committed)
git reset file-you-don't-want-to-commit
git status (to make sure only the files you want to commit are in the staging area)
git commit 
git push --force (--force is required because you re-wrote the commit locally and it is different now from the commit you pushed previously)

On GitHub you can double check that the commit you pushed looks good.  This pull request should update automatically to reflect the state of the branch you just pushed.  You could also close this one and open another one if you prefer.

Note that the git reset stuff only works in this case because the commit has not been merged yet and you are the only one that has it.  Once the commit has been merged into emufreak's iAmiga branch, it should never be re-written using get reset.

**Comment by simontoens** [comment]
@mithrendal I just updated the comment above

**Comment by simontoens** [comment]
Another note about git usage - before pushing to github and creating a pull request, you should rebase the latest changes that other people have made.  This ensures that the pull request you end up creating only has the commits you made for whatever you are working on (i.e. there won't be any of those "merge this into that" commits).

**Comment by simontoens** [comment]
I'd be happy to walk you through this over Skype or something, obviously there are lots of online resources also...

**Comment by mithrendal** [comment]
tried git reset --soft HEAD~ (this will undo your last commit and move the files back to the staging area)
git status (to see all the files that are staged to be committed)
git reset the project file
git status (to make sure only the files you want to commit are in the staging area)
git commit 
git push --force (--force is required because you re-wrote the commit locally and it is different now from the commit you pushed previously)

it ran through but still the project file is in the pull request.

I think the problem is that the project file has been committed not in the last commit but one before it. (In order to synchronize changes with emu freaks branch) So the reset command resets the file to an version which already has been altered by me. Is there a way to reset a file to the very first version ? 

I close the pull request now and try it again this evening ...

**Comment by mithrendal** [comment]
@simontoens 
I think my problem with your proposed reset, that  does not work is, that the project file has been committed not in the last commit but one before it. (In order to synchronize changes with emu freaks branch) (in fact I committed it twice) So the reset command resets the file to an version which already has been altered by me. Is there a way to reset a file to the very first version ?

**Comment by simontoens** [comment]
Yes, you can just use the the commit id sha directly.  Run git log, find the fist commit you want to undo, then run git reset sha-of-that-commit~.  The ~ means the commit right before, ie you want to reset the state to the commit right before the one that committed the project file.

~ means one commit before (parent commit), ~2 means two commits before (grandparent commit), etc.

**Comment by mithrendal** [comment]
@simontoens Thank you so much. I will try this out this evening. ;-)

**Comment by mithrendal** [comment]
@simontoens 
I did a "git reset sha..." to the very beginning and reseted the project file and discarded the changes to it.
I committed the uncommitted changes again and forced the push. Now the project file is gone. But now also the changes of the first pull request are in here, and also yours recent changes, is that ok?

Simon can you have a look please whether it is ok now for emu freak to pull ?

Sorry for the trouble I am an beginner with GIT.

**Comment by mithrendal** [comment]
@simontoens Ah I forgot to say I created a new pull request

**Pull request closed without merging**
