### PR TITLE
Add switches to disable drives.

### PR DESCRIPTION
**Pull request by simontoens**
Hi @emufreak,

This change adds switches next to df1-df3 so that they can be disabled.  I am not 100% sure I did this the right way but it seems to work.  
The state of the drives is not persisted, that would require additional work to interact with the code in disk.cpp.  I think that's ok for now - in most cases it is fine to leave all drives on anyway.

Regards -

### CODE REVIEW

**Comment by simontoens** [comment]
HI @emufreak, I have improved this a bit:
- Enabling/disabling drives (df1, df2, df3) can now only be done when resetting the emulator.  This ensures that the emulator is always in a good state with respect to which drives are enabled and which are disabled.
- Whether a drive is enabled or disabled is now persisted in Settings.  When "Autoload Config" is enabled, the state of the drives is restored from settings.

**Comment by simontoens** [comment]
@emufreak, I will take care of the merge conflicts and update this pull request.  Thanks for merging the other 2!

**Comment by emufreak** [comment]
Saw your message too late. Just resolved the merge conflicts

**Comment by simontoens** [comment]
@emufreak thanks!

**Pull request merged**
