### PR TITLE
zip/adf file associations and minor stuff

### PR DESCRIPTION
**Pull request by simontoens**
Hi @emufreak,

I wish I could create one pull-request per commit.  I don't think this is possible.  The larger change in this pull request is the ability to download (zipped) adfs using Safari.  For example, you can download Katakis from http://factor5.de/downloads.shtml, and the zip will be correctly handled by iUAE.  Of course, this is only for downloading adfs legally.

2 other minor things are:
- When going into settings and coming back, don't deselect the joystick button if it was selected.
- Support swipe-to-delete in the adf table view.

If these 2 changes above conflict with your refactor (maybe you are not using the view controllers anymore that I have changed), that is fine, they are really minor and can be re-done easily.

Regards

### CODE REVIEW

**Comment by emufreak** [comment]
Hi @simontoens 

Just tested the adf associations for r-type on factor5.de. After clicking on the download i get two options, open in or open in iFile. If i choose open in i get various suboptions of applications to use. Unfortunately iUAE is not one of them. Do you have any idea what went wrong here?

**Comment by simontoens** [comment]
I just tried this from scratch: I deleted my iAmiga repository, re-cloned my defender branch, deleted iUAE from my iPad, in Xcode I did Product->Clean followed by Product->Run (on iPad device).  When I click on "Download R-Type.zip" in Safari on my iPad, after a few seconds, I get the "open in iUAE" option.  So it works for me, unfortunately.  
Apparently I don't have any other applications registered to handle .zip - iUAE is the only option I get when clicking on the rtype download (see the screenshot).  Could you try changing the "handler rank" for .zip in iAmiga's Info.plist?  It is set to "Alternate" right now.  What happens if you set it to "Owner"?  See Info.plist -> Document types -> Item 0 (Zipped ADFs) -> Handler Rank.
screen shot 2015-04-06 at 1 44 37 pm

**Comment by emufreak** [comment]
Hi Simon. This fixes the problem. Thank you. I could Merge your pull request and fix the Info.plist in Version 1.1.0 or you could change your pull request. What do you think?

**Comment by simontoens** [comment]
@emufreak thank you for checking.  Interesting, so it only works for you if we say iUAE is the "owner" of the .zip extension.  This is not quite right but I am guessing this won't break anything either.  
I can fix this and re-create the pull request.  I think it would be better if I create the pull request directly against 1.1.0b1 correct?

**Comment by simontoens** [comment]
@emufreak I am curious, how does the "open in iUAE" option show up for you now?  Since iUAE is the "owner" now, what happened to iFile?  Is iFile still the first option?

**Comment by emufreak** [comment]
Ifile is still the first option, but iUAE is available now.

**Comment by simontoens** [comment]
Ok thanks - I will create a new pull request for 1.1.0b1 with the these changes and the change to Info.plist.

**Comment by emufreak** [comment]
Or we could add this to the main branch and release another minor Version. I think this would make sense in this case. Its only a small (but useful change). I don't see any reason to not release this to the public soon.

**Comment by simontoens** [comment]
Ok, let me make the change then and re-create the pull request against the defender branch.

**Comment by simontoens** [comment]
I keep forgetting that all I have to do is update the branch and push and the commit is automatically added to the pull request.  Ok, this should be it - I also tested it on my device.

**Pull request merged**
