### PR TITLE
Initial UI for state management

### PR DESCRIPTION
**Pull request by simontoens**
Hi @emufreak, this is not done but I think it is better to merge more often instead of waiting for too long.

This is the initial state management UI.  It only looks ok on iPad2.  

This also includes the sound related changes I made in the defender branch a while back. 

Right now if you want to try out saving states, you have to exit settings completely for the state to actually save.  

The next major things I plan on fixing are:
- Try to save the state right away, the moment the "save" button is pushed.
- Hook into what you have done for configurations to also store which disks are inserted when a state is saved.
- Work on UI for other devices - I will need to know how you plan on handling iPhone in general.  Another storyboard?  Also I noticed even iPad Air looks bad, something to look at...

### CODE REVIEW

**Comment by emufreak** [comment]
Hi @simontoens 

I planed on only using one storyboard. Simply because of the time it would take to handle more than one Storyboard. The time to create one storyboard seemed quite a task to me already. At least with the limited time I had do to it. I think we could make it work fairly well for all devices in the end,

It "works" on all devices already with this issues.

-Messed up Icons. It looks like this Issue is worse for Ipad Air than Ipad 2 for example. I plan on improving all the icons until the release though.

-For Iphone there is some Issue with scrolling. Last line of content is barely visible even if scrolling to the maximum. Do you have any idea how to fix this?

If you see any other Issues or points of improvement please tell me your suggestions.

**Comment by simontoens** [comment]
Ok sounds good - I will look into getting iPhone to work with the same storyboard.

**Comment by emufreak** [comment]
Hi @simontoens. What is not working for you on with the recent Storyboard on iPhone. With the exception of the Issue mentioned above it works fine for me.

**Comment by simontoens** [comment]
@emufreak you are right, I don't see any other major issues with iPhone apart from the scrolling issue you mention.  I don't know of a good solution but I will look at it a little.

The state management view I added doesn't look right on iPhone, so I need to fix that (I had 2 different .nib files in the defender branch); I will get to that soon.

**Comment by simontoens** [comment]
Hi @emufreak, I'd like to show some confirmation dialogs when loading and saving states - SVProgressHUD is very nice for this purpose (https://github.com/TransitApp/SVProgressHUD).  I have added it as a git submodule so you will have to run "git submodule init" followed by "git submodule update" once before you can build (after merging this pull request).  
I think we will find other places where we may want to use SVProgressHUD to show some some progress or confirmation dialogs so it is good to have it available... If however for some reason you don't like having this dependency, please let me know and I will remove it.

**Comment by emufreak** [comment]
Hi @simontoens, I'll merge this pull request now to make sure all recent development is included. Thanks

**Pull request merged**
